version: '3'
services:
  laravel:
    container_name: laravel
    build:
      context: ./
      dockerfile: ./php/Dockerfile
    working_dir: /var/www/app
    volumes:
    - ../:/var/www/app
    - ./apache/conf/apache2.conf:/etc/apache2/apache2.conf
    - ./apache/sites-enabled/:/etc/apache2/sites-enabled/
    ports:
      - 80:80
    networks:
      - backend
    depends_on:
      - redis
      - mysql
    restart: always
    environment:
      CONTAINER_ROLE: app
      TIME_ZONE: "Europe/Istanbul"

  scheduler:
    container_name: scheduler
    build:
      context: ./
      dockerfile: ./php/Dockerfile
    working_dir: /var/www/app
    depends_on:
      - laravel
    volumes:
    - ../:/var/www/app
    networks:
      - backend
    restart: always
    environment:
      CONTAINER_ROLE: scheduler
      TIME_ZONE: "Europe/Istanbul"

  queue:
    container_name: queue
    build:
      context: ./
      dockerfile: ./php/Dockerfile
    working_dir: /var/www/app
    depends_on:
    - laravel
    volumes:
    - ../:/var/www/app
    networks:
      - backend
    restart: always
    environment:
      CONTAINER_ROLE: queue
      TIME_ZONE: "Europe/Istanbul"

  mysql:
    container_name: mysql
    build:
      context: ./
      dockerfile: ./mysql/Dockerfile
    restart: always
    ports:
      - 33061:3306
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=apppass
    networks:
      - backend

  redis:
    container_name: redis
    build:
      context: ./
      dockerfile: ./redis/Dockerfile
    restart: always
    ports:
      - 6379:6379
    networks:
      - backend
    volumes:
      - ./redis/socket:/tmp/docker

networks:
    backend:
